package co.xarx.trix.domain;

public enum NotificationType {
	ADDED_TO_STATION,
	REMOVED_FROM_STATION,
	POST_COMMENTED,
	POST_DELETED,
	POST_ADDED,
	BREAKING_NEWS,
	MESSAGE,
	IREPORT_INVITE,
	IREPORT_REVOKE
}
